server:
  port: 8090
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: admin
  dbName: shopDevGo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  protocal: 3
databases:
  - user: root
    password: admin
    host: mysql
    dbName: shopDev
  - user: admin
    password: admin2
    host: mongodb
    dbName: shopDev
security:
  jwt:
    key: abc123
log:
  level: debug
  file_log_name: "./storages/logs/app.log"
  max_size: 100
  max_backups: 7
  max_age: 7
  compress: true