server:
  port: 8090
  mode: "dev"
mysql:
  host: 127.0.0.1
  port: 3306
  user: shopdev
  password: shopdev
  dbName: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  protocal: 3
databases:
  - user: shopdev
    password: admin
    host: mysql
    dbName: shopDev
  - user: admin
    password: admin2
    host: mongodb
    dbName: shopDev
rabbitmq:
  host: octopus-01.rmq3.cloudamqp.com
  port: 5671
  user: akpwryeb
  password: UiSkc1jO9GXYtkjH2PjOVRGRtW9pdmSg
  vhost: akpwryeb
security:
  jwt:
    key: abc123
log:
  level: debug
  file_log_name: "./storages/logs/app.log"
  max_size: 100
  max_backups: 7
  max_age: 7
  compress: true