server:
  port: 8090
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root1234
  dbName: shopDevGo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
databases:
  - user: admin
    password: admin
    host: mysql
    dbName: shopDev
  - user: admin
    password: admin2
    host: mongodb
    dbName: shopDev
security:
  jwt:
    key: abc123