@baseurl=http://localhost:8090/v1/2024


### User Health Check
GET {{baseurl}}/chekcStatus
Authorization: valid-token

### User Registration by Email
POST {{baseurl}}/user/register
Authorization: valid-token
Content-Type: application/json

{
    "email": "demo01@gmail.com",
    "purpose": "TEST-DEV444"
}

### User Registration Phone
POST {{baseurl}}/user/register
Authorization: valid-token
Content-Type: application/json

{
    "phone": "0383826639",
    "purpose": "TEST-DEV111"
}