@baseurl=http://localhost:8090/v1/2024


### User Health Check
GET {{baseurl}}/chekcStatus
Authorization: valid-token

### User Registration by Email
POST {{baseurl}}/user/register
Authorization: valid-token
Content-Type: application/json

{
    "verify_key": "demo01@gmail.com",
    "verify_type": 1,
    "verify_purpose": "TEST_USER"
}

### User Registration Phone
POST {{baseurl}}/user/register
Authorization: valid-token
Content-Type: application/json

{
    "verify_key": "0383826639",
    "verify_type": 2,
    "verify_purpose": "TEST_USER"
}